export const Schedule = [
    {
        duration: 0.75,
        imageURL: '/img/1-preshow.png',
        event: 'Preshow',
        console: 'Video',
        who: '',
        time: '2024-05-03T19:30:00.000Z',
    },
    {
        duration: 1.5,
        imageURL: '/img/2-warioware.png',
        event: 'WarioWare: Move It!',
        console: 'Switch',
        who: 'Everyone',
        time: '2024-05-03T20:15:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/3-megamanx2.png',
        event: 'Mega Man X2',
        console: 'SNES',
        who: 'Snoopy',
        time: '2024-05-03T21:45:00.000Z',
    },
    {
        duration: 1.75,
        imageURL: '/img/4-spicymariokart.png',
        event: 'Spicy Mario Kart',
        console: 'Switch',
        who: 'Everyone',
        time: '2024-05-03T22:45:00.000Z',
    },
    {
        duration: 2,
        imageURL: '/img/12-pokemon.png',
        event: 'Pokemon Super Kaizo Ironmon',
        console: 'PC',
        who: 'HoopsNL',
        time: '2024-05-04T00:30:00.000Z',
    },
    {
        duration: 4,
        imageURL: '/img/6-blkops3zoms.png',
        event: 'Call of Duty Black Ops 3 Zombies',
        console: 'PC',
        who: 'Smackdown',
        time: '2024-05-04T02:30:00.000Z',
    },
    {
        duration: 1.5,
        imageURL: '/img/7-doggonegolf.png',
        event: 'Dog Gone Golfing',
        console: 'Switch',
        who: 'Everyone',
        time: '2024-05-04T06:30:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/8-little2left.png',
        event: 'A Little to the Left + NICK SLEEP CAM',
        console: 'Switch',
        who: 'Skeeter',
        time: '2024-05-04T08:00:00.000Z',
    },
    {
        duration: 1.5,
        imageURL: '/img/9-fivenightfreddys.png',
        event: "Five Nights at Freddy's",
        console: 'PC',
        who: 'Gecko',
        time: '2024-05-04T09:00:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/10-huntgame.png',
        event: 'Hunter Call of the Wild',
        console: 'Xbox',
        who: 'Hackaman',
        time: '2024-05-04T10:30:00.000Z',
    },
    {
        duration: 2.5,
        imageURL: '/img/11-jeopardyc.png',
        event: 'Jeopardy Tournament of Champions',
        console: 'Switch',
        who: 'Everyone',
        time: '2024-05-04T11:30:00.000Z',
    },
    {
        duration: 2,
        imageURL: '/img/12-pokemon.png',
        event: 'Pokemon Super Kaizo Ironmon',
        console: 'PC',
        who: 'Mik Pickle',
        time: '2024-05-04T14:00:00.000Z',
    },
    {
        duration: 2.5,
        imageURL: '/img/13-overcooked.png',
        event: 'Overcooked',
        console: 'Switch',
        who: 'Skeeter and Marley',
        time: '2024-05-04T16:00:00.000Z',
    },
    {
        duration: 1.75,
        imageURL: '/img/14-mariomaker.png',
        event: 'Mario Maker Solos',
        console: 'Switch',
        who: 'Everyone',
        time: '2024-05-04T18:30:00.000Z',
    },
    {
        duration: 3,
        imageURL: '/img/15-metroiddread.png',
        event: 'Metroid Dread',
        console: 'Switch',
        who: 'CoPilot',
        time: '2024-05-04T20:15:00.000Z',
    },
    {
        duration: 1.75,
        imageURL: '/img/16-dkc2.png',
        event: 'Donkey Kong Country 2',
        console: 'SNES',
        who: 'Vedder',
        time: '2024-05-04T23:15:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/17-worms.png',
        event: 'Worms WMD',
        console: 'Switch',
        who: 'Windsock, Squiggles, Mik Pickle, Peter Pan',
        time: '2024-05-05T01:00:00.000Z',
    },
    {
        duration: 4,
        imageURL: '/img/18-castlecrashers.png',
        event: 'Castle Crashers',
        console: 'Xbox One',
        who: 'Skitch, Dingus, Aux',
        time: '2024-05-05T02:00:00.000Z',
    },
    {
        duration: 1.5,
        imageURL: '/img/19-leaguelegends.png',
        event: 'League of Legends ARAMS',
        console: 'PC',
        who: 'Busk',
        time: '2024-05-05T06:00:00.000Z',
    },
    {
        duration: 2,
        imageURL: '/img/20-marioparty.png',
        event: 'Mario Party Superstars',
        console: 'Switch',
        who: 'Everyone',
        time: '2024-05-05T07:30:00.000Z',
    },
    {
        duration: 3,
        imageURL: '/img/21-eldenring.png',
        event: 'Elden Ring',
        console: 'PS5',
        who: 'Hiker',
        time: '2024-05-05T09:30:00.000Z',
    },
    {
        duration: 2,
        imageURL: '/img/22-megamanx.png',
        event: 'Mega Man X',
        console: 'SNES?',
        who: 'KZ',
        time: '2024-05-05T12:30:00.000Z',
    },
    {
        duration: 1.75,
        imageURL: '/img/23-fnafsb.png',
        event: 'FNAF Security Breach',
        console: 'PC',
        who: 'Gecko',
        time: '2024-05-05T14:30:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/24-mmprtm.png',
        event: 'Mighty Morphin Power Rangers The Movie',
        console: 'SNES',
        who: 'Mik Pickle, Pokey',
        time: '2024-05-05T16:15:00.000Z',
    },
    {
        duration: 1.5,
        imageURL: '/img/25-horsechicken.png',
        event: 'Ultimate Chicken Horse Game',
        console: 'Switch',
        who: 'Everyone',
        time: '2024-05-05T17:15:00.000Z',
    },
    {
        duration: 0.75,
        imageURL: '/img/26-astrosplay.png',
        event: "Astro's Playroom",
        console: 'PS5',
        who: 'Lettuce',
        time: '2024-05-05T18:45:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/27-12switch.png',
        event: '1 2 Switch',
        console: 'Switch',
        who: 'Windsock, Squiggles, Skitch, Pokey',
        time: '2024-05-05T19:30:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/28-assassinscreed.png',
        event: "Assassin's Creed",
        console: 'Xbox One',
        who: 'Sarge',
        time: '2024-05-05T20:30:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/1-preshow.png',
        event: 'Half time Show',
        console: 'IRL',
        who: '',
        time: '2024-05-05T21:30:00.000Z',
    },
    {
        duration: 3,
        imageURL: '/img/1-preshow.png',
        event: 'The Gaming Olympics',
        console: 'IRL',
        who: 'Everyone',
        time: '2024-05-05T22:30:00.000Z',
    },
    {
        duration: 2,
        imageURL: '/img/29-balatro.png',
        event: 'Balatro',
        console: 'PC',
        who: 'Moonlight',
        time: '2024-05-06T01:30:00.000Z',
    },
    {
        duration: 4,
        imageURL: '/img/30-bindingofisaac.png',
        event: 'Binding of Issac',
        console: 'PC',
        who: 'Smackdown',
        time: '2024-05-06T03:30:00.000Z',
    },
    {
        duration: 1.75,
        imageURL: '/img/1-preshow.png',
        event: 'Racing Wheel',
        console: 'PC',
        who: 'Everyone',
        time: '2024-05-06T07:30:00.000Z',
    },
    {
        duration: 1.75,
        imageURL: '/img/31-haloinfinite.png',
        event: 'Halo Infinite',
        console: 'PC',
        who: 'Aux',
        time: '2024-05-06T09:15:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/32-clubpenguin.png',
        event: 'Club Penguin',
        console: 'PC',
        who: 'Oasis',
        time: '2024-05-06T11:00:00.000Z',
    },
    {
        duration: 6,
        imageURL: '/img/33-ffx.png',
        event: 'Final Fantasy X',
        console: 'PC',
        who: 'Pokey',
        time: '2024-05-06T12:00:00.000Z',
    },
    {
        duration: 1.5,
        imageURL: '/img/34-lethalcompany.png',
        event: 'Lethal Company',
        console: 'PC',
        who: 'Majora',
        time: '2024-05-06T18:00:00.000Z',
    },
    {
        duration: 0.5,
        imageURL: '/img/1-preshow.png',
        event: 'Super Fancy Pants Adventures',
        console: 'PC',
        who: 'Lettuce',
        time: '2024-05-06T19:30:00.000Z',
    },
    {
        duration: 2,
        imageURL: '/img/35-rhythmheaven.png',
        event: 'Rhythm Heaven Fever',
        console: 'Wii',
        who: 'CoPilot, Bestea',
        time: '2024-05-06T20:00:00.000Z',
    },
    {
        duration: 1.5,
        imageURL: '/img/14-mariomaker.png',
        event: 'Mario Maker Groups',
        console: 'Switch',
        who: 'Everyone',
        time: '2024-05-06T22:00:00.000Z',
    },
    {
        duration: 1.25,
        imageURL: '/img/36-linkcrosstraining.png',
        event: "Link's Crossbow Training",
        console: 'Wii',
        who: 'Majora',
        time: '2024-05-06T23:30:00.000Z',
    },
    {
        duration: 3.25,
        imageURL: '/img/37-oot.png',
        event: 'Ocarina of time',
        console: 'Wii',
        who: 'Mik Pickle',
        time: '2024-05-07T00:45:00.000Z',
    },
    {
        duration: 1.25,
        imageURL: '/img/38-speedrunners.png',
        event: 'Speedrunners',
        console: 'Switch',
        who: 'Everyone',
        time: '2024-05-07T04:00:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/39-portal.png',
        event: 'Portal',
        console: 'PC',
        who: 'Gambino',
        time: '2024-05-07T05:15:00.000Z',
    },
    {
        duration: 2,
        imageURL: '/img/40-trash.png',
        event: 'Garbage Games',
        console: 'Gamecube',
        who: 'Everyone',
        time: '2024-05-07T06:15:00.000Z',
    },
    {
        duration: 0.75,
        imageURL: '/img/41-wiiplay.png',
        event: 'Wii Play',
        console: 'Wii',
        who: 'Baked Potato, Two Headed Boy',
        time: '2024-05-07T08:15:00.000Z',
    },
    {
        duration: 1.75,
        imageURL: '/img/42-switchsports.png',
        event: 'Switch Sports',
        console: 'Switch',
        who: 'Everyone',
        time: '2024-05-07T09:00:00.000Z',
    },
    {
        duration: 2,
        imageURL: '/img/43-stray.png',
        event: 'Stray',
        console: 'PS5',
        who: 'Gambino',
        time: '2024-05-07T10:45:00.000Z',
    },
    {
        duration: 5,
        imageURL: '/img/44-hogwartslegacy.png',
        event: 'Hogwarts Legacy',
        console: 'PC',
        who: 'Busk',
        time: '2024-05-07T12:45:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/45-stardew.png',
        event: 'Stardew Valley',
        console: 'Switch',
        who: 'Jughead',
        time: '2024-05-07T17:45:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/46-turnipboy.png',
        event: 'Turnip Boy Commits Tax Evasion',
        console: 'PS5',
        who: 'Gambino',
        time: '2024-05-07T18:45:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/47-tastetest.png',
        event: "Thrill's Taste Test",
        console: 'IRL',
        who: 'The Thrill',
        time: '2024-05-07T19:45:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/48-nobodyexplodes.png',
        event: 'Keep Talking and Nobody Explodes',
        console: 'PC',
        who: 'Everyone',
        time: '2024-05-07T20:45:00.000Z',
    },
    {
        duration: 1,
        imageURL: '/img/49-heaveho.png',
        event: 'Heave Ho',
        console: 'Switch',
        who: 'Everyone',
        time: '2024-05-07T21:45:00.000Z',
    },
    {
        duration: 0.75,
        imageURL: '/img/50-royalrumble.png',
        event: 'Royal Rumble + Finale',
        console: 'IRL',
        who: 'Everyone',
        time: '2024-05-07T22:45:00.000Z',
    },
]
